//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CoreModel.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CONFIGSEL_DIALOG            102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDD_BITETHRESHOLDDIALOG         129
#define IDR_CoreModelTYPE               130
#define IDD_LEFTRIGHTBOTHDIALOG         130
#define IDD_HLDIALOG                    131
#define IDD_TLDIALOG                    132
#define IDD_PUBLICDIALOG                133
#define ID_VIEW_OUTPUTWND               149
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDD_BASETRAINWND                310
#define ID_START                        311
#define IDB_BOPER                       311
#define ID_ZOOMOUT                      312
#define IDD_INITDLG                     312
#define ID_ZOOMIN                       313
#define ID_PAUSE                        314
#define ID_STOP                         315
#define ID_COLORPANE                    316
#define ID_DRAWFLAGE                    317
#define IDD_DEVICESELDLG                318
#define MYWM_MAINFRAMINNER              319
#define INNERMAINFRAME_UPDATA           320
#define IDD_VIEWERSELDLG                321
#define VIEWSELDLG_CHECK                322
#define INNERMAINFRAME_CMDCODE          323
#define IDC_EUSERNAME                   1000
#define IDC_TAB1                        1000
#define IDC_COMBOUSERLIST               1001
#define IDC_CHECKUSER                   1002
#define IDC_EDEVSEARCHDIR               1003
#define IDC_BLeftTLParmaPath            1003
#define IDC_BDEVSEARCHDIR               1004
#define IDC_EOverLappedWinLen           1004
#define IDC_COMDEVSEL                   1005
#define IDC_BLeftTLDataPath             1005
#define IDC_EBothDataPath               1005
#define IDC_COMDEVSAMPLERATE            1006
#define IDC_ELeftThreshold              1006
#define IDC_EDEVCHANNELS                1007
#define IDC_BBothTLParamPath            1007
#define IDC_ERightDataPath              1007
#define IDC_ERightThreshold             1008
#define IDC_RDEVNORMAL                  1009
#define IDC_EBothTLDataPath             1009
#define IDC_RDEVIMP                     1010
#define IDC_RTLTrain                    1010
#define IDC_EDEVBUFFERSIZE              1011
#define IDC_RTLNoTrain                  1011
#define IDC_EVIEWSEARCHDIR              1012
#define IDC_BBothTLDataPath             1012
#define IDC_BVIEWSEARCHDIR              1013
#define IDC_BRightTLParamPath           1013
#define IDC_COMVIEWMODEL                1014
#define IDC_BRightTLDataPath            1014
#define IDC_EVIEWMESSAGE                1015
#define IDC_BLeftModelPath              1015
#define IDC_EDITVIEWLENGTH              1016
#define IDC_RTLReTrain                  1016
#define IDC_EDITVIEWWIDTH               1017
#define IDC_RHLNoReTrain                1017
#define IDC_EVIEWMAX                    1018
#define IDC_ERightTLParamPath           1018
#define IDC_EVIEWMIN                    1019
#define IDC_CHKVIEWAUTO                 1020
#define IDC_ELeftModelPath              1020
#define IDC_EWindowLength               1020
#define IDC_ERightModelPath             1021
#define IDC_BRightModelPath             1022
#define IDC_ELPARAM                     1022
#define IDC_EBothModelPath              1023
#define IDC_BUTTON1                     1023
#define IDC_BLPARAM                     1023
#define IDC_BBothModelPath              1024
#define IDC_BTLModulePath               1026
#define IDC_BBiteDataPath               1027
#define IDC_BBiteThroldPath             1028
#define IDC_BBiteThroldModulePath       1029
#define IDC_EBiteDataPath               1032
#define IDC_EBiteThroldPath             1033
#define IDC_EThroldMoudelPath           1034
#define IDC_EBiteTrainTime              1039
#define IDC_EBiteCount                  1040
#define IDC_EModelTrainTime             1041
#define IDC_EModelPath                  1042
#define IDC_ELeftDataPath               1043
#define IDC_EModulePath                 1044
#define IDC_BModelPath                  1045
#define IDC_BLeftDataPath               1046
#define IDC_BRightDataPath              1047
#define IDC_BBothDataPath               1048
#define IDC_BModulePath                 1049
#define IDC_EHLTrainTime                1050
#define IDC_EHLModelPath                1051
#define IDC_EHLModulePath               1052
#define IDC_ELeftLightDataPath          1053
#define IDC_ELeftHeavyDataPath          1054
#define IDC_ERightLightDataPath         1055
#define IDC_ERightHeavyDataPath         1056
#define IDC_EBothLightDataPath          1057
#define IDC_EBothHeavyDataPath          1058
#define IDC_BHLModelPath                1059
#define IDC_BHLModulePath               1060
#define IDC_BLeftLightDataPath          1061
#define IDC_BLeftHeavyDataPath          1062
#define IDC_BRightLightDataPath         1063
#define IDC_BRightHeavyDataPath         1064
#define IDC_BBothLightDataPath          1065
#define IDC_BBothHeavyDataPath          1066
#define IDC_ETwoBiteTrainTime           1067
#define IDC_ELeftTLParmaPath            1068
#define IDC_ETLModulePath               1069
#define IDC_ELeftTLDataPath             1070
#define IDC_EBothTLParamPath            1071
#define IDC_ERightTLDataPath            1072
#define IDC_RBiteTrain                  1073
#define IDC_RBiteNotTrain               1074
#define IDC_RTLNoReTrain                1078
#define IDC_RModelTrain                 1079
#define IDC_RModelNotTrain              1080
#define IDC_RModelReTrain               1081
#define IDC_RModelNoReTrain             1082
#define IDC_RHLTrain                    1083
#define IDC_RHLNoTrain                  1084
#define IDC_RHLReTrain                  1085
#define ID_DEVICESETTING_SELDEVICE      32771
#define ID_SETTING_ALOGRITHM            32772
#define ID_SETTING_APPLICATION          32773
#define ID_SETTING_EEGVIEWER            32774
#define ID_TRAINING_TRAINSETTING        32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           324
#endif
#endif
